apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mattermost-db
  namespace: mattermost
  labels:
    app: mattermost-maher
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
